id: e308a2d2314b40f09c2a5ecc5cf37762
initial_creation_type: ocr
source_metadata:
  volumes:
    c1b238dc23614144baf6252243ebd7bb:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      volume_number: 67
